import { useEffect,useRef } from 'react';
import { Link } from 'react-router-dom';
export default function ExportStory({en}){
 const root=useRef(null);
 useEffect(()=>{let raf=0;const update=()=>{raf=0;const el=root.current;const header=innerWidth<=760?72:88;const p=Math.max(0,Math.min(1,(header-el.getBoundingClientRect().top)/((el.offsetHeight-el.querySelector(".export-stage").offsetHeight)*.72)));el.style.setProperty('--export-p',p);};const scroll=()=>{if(!raf)raf=requestAnimationFrame(update);};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{removeEventListener('scroll',scroll);removeEventListener('resize',scroll);cancelAnimationFrame(raf);};},[]);
 return <section ref={root} className="export-story"><div className="export-stage"><img className="export-background" src="./assets/renewal/export-port.jpg" alt={en?'Concept image of Korean exports by sea':'한국에서 세계로 향하는 수출 항만 콘셉트 이미지'}/><div className="export-shade"/>
 <div className="export-copy"><span className="story-eyebrow">FROM KOREA, TO THE WORLD</span><h2>{en?<>Care that begins here.<br/>Reaching the world.</>:<>한국에서 시작한 진심,<br/>세계의 일상으로.</>}</h2><p>{en?'Connecting trusted pet care with partners around the world.':'믿을 수 있는 펫 케어를 더 넓은 세상으로.\n부명과 함께 성장할 글로벌 파트너를 기다립니다.'}</p><Link to="/contact" className="renew-button light">{en?'Become a partner':'파트너십 문의하기'} ↗</Link></div>
 <div className="export-network" aria-hidden="true"><svg viewBox="0 0 1000 600"><defs><radialGradient id="globe-fill"><stop stopColor="#72d6ee" stopOpacity=".18"/><stop offset="1" stopColor="#0a4269" stopOpacity=".06"/></radialGradient></defs><circle cx="590" cy="310" r="240" fill="url(#globe-fill)" stroke="#9de5ff44"/><ellipse cx="590" cy="310" rx="130" ry="240"/><ellipse cx="590" cy="310" rx="225" ry="90"/><path d="M350 310H830M590 70V550"/>{['M680 270 Q540 45 410 235','M680 270 Q815 90 850 325','M680 270 Q550 170 515 455','M680 270 Q410 280 350 375'].map(d=><path key={d} d={d} className="export-route" pathLength="1"/>)}<circle cx="680" cy="270" r="8" fill="white"/><circle cx="680" cy="270" r="22" stroke="white"/><text x="700" y="265">KOREA</text><text x="430" y="590">GLOBAL PARTNERSHIP</text></svg></div>
 </div></section>;
}
